### ISSUE TITLE
Metadata Update

### ISSUE THREAD

**Issue by reeshmabijosh** [JohnGBaker/MoCoCovid#1]
Hello,
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/KGD6UL
Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by JohnGBaker** [comment]
This dataset does not provide any original content it is just an extract of data obtained from official reporting my the state of Maryland, as relevant to Montgomery County and zip code 20853, collected here for my own convenience.  It would be better to obtain the data (and much more) directly from coronavirus.maryland.gov
